# generate_data.ps1
# ---------------------------------------------------------------
# Wraps api.json into data.js so the skill browser works when
# opened via file:// (Chrome blocks fetch() on the file:// scheme).
#
# Run this script once after each game build / api.json update:
#   .\generate_data.ps1
#
# The output data.js is loaded by index.html before app.js.
# When served over HTTP (start_server.bat), fetch('./api.json')
# is used as a fallback and data.js is not required.
# ---------------------------------------------------------------

param(
    [string]$ApiPath    = "$PSScriptRoot\api.json",
    [string]$OutputPath = "$PSScriptRoot\data.js"
)

if (-not (Test-Path $ApiPath)) {
    Write-Error "api.json not found at: $ApiPath"
    exit 1
}

$json = Get-Content -Path $ApiPath -Raw -Encoding UTF8

$output = @"
// AUTO-GENERATED by generate_data.ps1 — do not edit manually.
// Re-run the script after updating api.json.
window.SIC_DATA = $json;
"@

[System.IO.File]::WriteAllText($OutputPath, $output, [System.Text.Encoding]::UTF8)

$size = [math]::Round((Get-Item $OutputPath).Length / 1KB, 1)
Write-Host "OK: data.js written ($size KB) -> $OutputPath" -ForegroundColor Green


