#!/usr/bin/env python3
"""
start.py
--------
1. Wraps api.json into data.js so the skill browser works when opened via
   file:// (Chrome blocks fetch() on the file:// scheme).
2. Starts a local HTTP server so the browser can also load the app over HTTP
   with fetch('./api.json') as the live data source.

Usage:
    python start.py            # generate data.js + serve on port 8080
    python start.py --port 9000
    python start.py --no-server  # only regenerate data.js, then exit
"""

import argparse
import http.server
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_API_PATH = os.path.join(SCRIPT_DIR, "api.json")
DEFAULT_OUTPUT_PATH = os.path.join(SCRIPT_DIR, "data.js")
DEFAULT_PORT = 8080


def generate_data_js(api_path: str = DEFAULT_API_PATH,
                     output_path: str = DEFAULT_OUTPUT_PATH) -> None:
    """Read api.json and write data.js with window.SIC_DATA assigned."""
    if not os.path.exists(api_path):
        print(f"ERROR: api.json not found at: {api_path}", file=sys.stderr)
        sys.exit(1)

    with open(api_path, "r", encoding="utf-8") as f:
        raw_json = f.read()

    # Validate JSON before writing
    json.loads(raw_json)

    output = (
        "// AUTO-GENERATED by start.py — do not edit manually.\n"
        "// Re-run the script after updating api.json.\n"
        f"window.SIC_DATA = {raw_json};\n"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output)

    size_kb = round(os.path.getsize(output_path) / 1024, 1)
    print(f"OK: data.js written ({size_kb} KB) -> {output_path}")


def serve(port: int = DEFAULT_PORT) -> None:
    """Change to the script directory and start an HTTP server."""
    os.chdir(SCRIPT_DIR)

    handler = http.server.SimpleHTTPRequestHandler

    print("-----------------------------------------------")
    print(" Second-in-Command Skill Browser")
    print(f" http://localhost:{port}")
    print(" Press Ctrl+C to stop")
    print("-----------------------------------------------")

    with http.server.HTTPServer(("", port), handler) as httpd:
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nServer stopped.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate data.js and optionally serve the SIC skill browser."
    )
    parser.add_argument(
        "--api", default=DEFAULT_API_PATH,
        help=f"Path to api.json (default: {DEFAULT_API_PATH})"
    )
    parser.add_argument(
        "--output", default=DEFAULT_OUTPUT_PATH,
        help=f"Path for the generated data.js (default: {DEFAULT_OUTPUT_PATH})"
    )
    parser.add_argument(
        "--port", type=int, default=DEFAULT_PORT,
        help=f"HTTP server port (default: {DEFAULT_PORT})"
    )
    parser.add_argument(
        "--no-server", action="store_true",
        help="Only regenerate data.js and exit without starting the server."
    )
    args = parser.parse_args()

    generate_data_js(args.api, args.output)

    if not args.no_server:
        serve(args.port)


if __name__ == "__main__":
    main()

